spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/bootex
    username: bootuser
    password: bootuser
  #    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  thymeleaf:
    cache: false

# 파일 업로드를 위한 설정(387p)
  servlet:
    multipart:
      enabled: true                  # 파일 업로드 가능 여부를 선택
      location: C:\\upload           # 업로드된 파일의 임시 저장 경로
      max-request-size: 30MB         # 한번에 최대 업로드 가능 용량
      max-file-size: 10MB



# 서버 설정
server:
  port: 8282
  error:
    include-exception: false       # 오류 응답에 exception의 내용을 포함할지 여부(끔)
    include-stacktrace: never      # 오류 응답에 stacktrace 내용을 포함할지 여부(끔)
#    path:                          # 오류 응담을 처리할 핸들러(ErrorController)의 path(경로)
#    whitelabel:
#      enabled:  # 브라우저 요청에 대해 서버 오류시 기본으로 노출할 페이지를 사용할지 여부

# 업로드된 파일의 저장, 신규 작성(393p)
org:
  syc:
    upload:
      path: C:\\upload